version: '3.8'

services:
  neonswap:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: neonswap-game
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "com.docker.compose.project=neonswap"
      - "description=NeonSwap Flutter Game"
