providers = ["dart"]

[variables]
DART_SDK_VERSION = "3.2.6"
FLUTTER_VERSION = "3.16.9"

[phases.setup]
nixPkgs = [
  "dart",
  "flutter",
  "git",
  "curl",
  "unzip",
  "wget"
]
aptPkgs = [
  "ca-certificates"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "flutter doctor --android-licenses || true",
  "dart pub get"
]

[phases.build]  
dependsOn = ["install"]
cmds = [
  "flutter build web --release"
]

[start]
cmd = "cd build/web && python3 -m http.server 8080"
