providers = ["dart"]

[variables]
DART_SDK_VERSION = "3.2.6"
FLUTTER_VERSION = "3.16.9"
FLUTTER_ROOT = "/nix/store"
PUB_CACHE = "/tmp/.pub-cache"
FLUTTER_WEB_USE_SKIA = "true"
CHROME_EXECUTABLE = "/usr/bin/google-chrome-stable"

[phases.setup]
nixPkgs = [
  "flutter",
  "git",
  "curl",
  "unzip",
  "wget",
  "python3",
  "nodejs_18",
  "jq",
  "which"
]
aptPkgs = [
  "ca-certificates",
  "libc6-dev",
  "libglu1-mesa",
  "build-essential",
  "libgtk-3-dev",
  "libblkid1",
  "liblzma5"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "flutter config --no-analytics",
  "flutter config --enable-web",
  "flutter doctor -v || true",
  "flutter --version",
  "dart --version",
  "flutter clean",
  "flutter pub get",
  "flutter pub deps"
]

[phases.build]  
dependsOn = ["install"]
cmds = [
  "flutter build web --release --web-renderer html --no-tree-shake-icons",
  "ls -la build/web/",
  "echo 'Build completed successfully'"
]

[start]
cmd = "cd build/web && python3 -m http.server 8080 --bind 0.0.0.0"
