providers = ["dart"]

[variables]
DART_SDK_VERSION = "3.2.6"
FLUTTER_VERSION = "3.16.9"

[phases.setup]
nixPkgs = [
  "dart_3-2-6",
  "flutter",
  "git",
  "curl",
  "unzip"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "dart pub get"
]

[phases.build]  
dependsOn = ["install"]
cmds = [
  "flutter build web --release"
]

[start]
cmd = "flutter run --web-port=8080 --web-hostname=0.0.0.0"
