name: neonswap
description: Neon Runner implementation using Flame Engine
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  vector_math: ^2.1.4
  flutter_bloc: ^8.1.6
  flame_audio: ^2.1.8
  yaml: ^3.1.2
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - config/
